version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketAPI/Dockerfile

  discountapi:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/DiscountAPI/Dockerfile

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin-data: