<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SqlQueries\CreateDiscountCoupon.sql" />
    <None Remove="SqlQueries\DeleteDiscountCoupon.sql" />
    <None Remove="SqlQueries\UpdateDiscountCoupon.sql" />
    <None Remove="SqlQueries\VerifyCoupon.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SqlQueries\CreateDiscountCoupon.sql" />
    <EmbeddedResource Include="SqlQueries\DeleteDiscountCoupon.sql" />
    <EmbeddedResource Include="SqlQueries\UpdateDiscountCoupon.sql" />
    <EmbeddedResource Include="SqlQueries\VerifyCoupon.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Npgsql" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>


</Project>
